name: Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      - run: npm run test:ci
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Report
          path: '**/test-report.xml'
          reporter: jest-junit