name: Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      - run: npm run test:ci
      #      - name: Publish Test Report
      #        uses: mikepenz/action-junit-report@v2
      #        if: always() # always run even if the previous step fails
      #        with:
      #          report_paths: '**/junit.xml'
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: '**/junit.xml'    # Path to test results
          reporter: jest-junit        # Format of test results